import { Injectable, Logger } from '@nestjs/common';
import { WhiteLabelService } from './white-label.service';
import { WhiteLabelConfigDto } from '../dto/white-label-config.dto';

export interface ReportBrandingConfig {
  showPlatformBranding: boolean;
  companyName: string;
  logoUrl?: string;
  primaryColor: string;
  secondaryColor: string;
  headerText?: string;
  footerText?: string;
  watermark?: string;
}

@Injectable()
export class ReportBrandingService {
  private readonly logger = new Logger(ReportBrandingService.name);

  constructor(private whiteLabelService: WhiteLabelService) {}

  /**
   * Get branding configuration for reports
   */
  async getReportBranding(workspaceId: string): Promise<ReportBrandingConfig> {
    let whiteLabelConfig: WhiteLabelConfigDto | null = null;

    try {
      whiteLabelConfig = await this.whiteLabelService.getWhiteLabelConfig(workspaceId);
    } catch (error) {
      // If white-label config is not available, use default branding
      this.logger.warn(`White-label config not available for workspace ${workspaceId}, using defaults`);
    }

    return this.buildReportBranding(whiteLabelConfig);
  }

  /**
   * Build report branding configuration
   */
  private buildReportBranding(whiteLabelConfig: WhiteLabelConfigDto | null): ReportBrandingConfig {
    const defaultBranding: ReportBrandingConfig = {
      showPlatformBranding: true,
      companyName: 'Social Media Platform',
      logoUrl: 'https://platform.com/logo.png',
      primaryColor: '#3B82F6',
      secondaryColor: '#10B981',
      headerText: 'Social Media Analytics Report',
      footerText: 'Generated by Social Media Platform',
      watermark: 'Powered by Social Media Platform',
    };

    if (!whiteLabelConfig || !whiteLabelConfig.enabled) {
      return defaultBranding;
    }

    return {
      showPlatformBranding: !whiteLabelConfig.hidePlatformBranding,
      companyName: whiteLabelConfig.companyName || defaultBranding.companyName,
      logoUrl: whiteLabelConfig.logoUrl || defaultBranding.logoUrl,
      primaryColor: whiteLabelConfig.colors?.primary || defaultBranding.primaryColor,
      secondaryColor: whiteLabelConfig.colors?.secondary || defaultBranding.secondaryColor,
      headerText: `${whiteLabelConfig.companyName || 'Social Media'} Analytics Report`,
      footerText: whiteLabelConfig.hidePlatformBranding
        ? `Generated by ${whiteLabelConfig.companyName || 'Your Company'}`
        : defaultBranding.footerText,
      watermark: whiteLabelConfig.hidePlatformBranding
        ? undefined
        : defaultBranding.watermark,
    };
  }

  /**
   * Generate PDF report header HTML
   */
  async generateReportHeader(workspaceId: string, reportTitle: string): Promise<string> {
    const branding = await this.getReportBranding(workspaceId);

    return `
      <div style="background-color: ${branding.primaryColor}; padding: 30px; color: white; text-align: center;">
        ${branding.logoUrl ? `<img src="${branding.logoUrl}" alt="${branding.companyName}" style="max-width: 200px; margin-bottom: 20px;">` : ''}
        <h1 style="margin: 0; font-size: 28px;">${reportTitle}</h1>
        <p style="margin: 10px 0 0 0; font-size: 16px;">${branding.headerText}</p>
      </div>
    `;
  }

  /**
   * Generate PDF report footer HTML
   */
  async generateReportFooter(workspaceId: string): Promise<string> {
    const branding = await this.getReportBranding(workspaceId);

    return `
      <div style="background-color: #f9fafb; padding: 20px; text-align: center; font-size: 12px; color: #6b7280; border-top: 1px solid #e5e7eb;">
        <p style="margin: 0;">${branding.footerText}</p>
        ${branding.watermark ? `<p style="margin: 5px 0 0 0; font-size: 10px;">${branding.watermark}</p>` : ''}
        <p style="margin: 5px 0 0 0;">Generated on ${new Date().toLocaleDateString()}</p>
      </div>
    `;
  }

  /**
   * Generate CSS styles for report
   */
  async generateReportStyles(workspaceId: string): Promise<string> {
    const branding = await this.getReportBranding(workspaceId);

    return `
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
          color: #374151;
          line-height: 1.6;
          margin: 0;
          padding: 0;
        }
        .report-container {
          max-width: 1200px;
          margin: 0 auto;
          background-color: white;
        }
        .report-section {
          padding: 30px;
          border-bottom: 1px solid #e5e7eb;
        }
        .report-section:last-child {
          border-bottom: none;
        }
        h1, h2, h3 {
          color: ${branding.primaryColor};
          margin-top: 0;
        }
        .metric-card {
          background-color: #f9fafb;
          border-radius: 8px;
          padding: 20px;
          margin: 10px 0;
          border-left: 4px solid ${branding.primaryColor};
        }
        .metric-value {
          font-size: 32px;
          font-weight: bold;
          color: ${branding.primaryColor};
        }
        .metric-label {
          font-size: 14px;
          color: #6b7280;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        .chart-container {
          margin: 20px 0;
          padding: 20px;
          background-color: #f9fafb;
          border-radius: 8px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 20px 0;
        }
        th {
          background-color: ${branding.primaryColor};
          color: white;
          padding: 12px;
          text-align: left;
          font-weight: 600;
        }
        td {
          padding: 12px;
          border-bottom: 1px solid #e5e7eb;
        }
        tr:hover {
          background-color: #f9fafb;
        }
        .highlight {
          background-color: ${branding.secondaryColor}20;
          padding: 2px 6px;
          border-radius: 4px;
        }
        .page-break {
          page-break-after: always;
        }
      </style>
    `;
  }

  /**
   * Generate complete branded report HTML
   */
  async generateBrandedReport(
    workspaceId: string,
    reportTitle: string,
    reportContent: string,
  ): Promise<string> {
    const header = await this.generateReportHeader(workspaceId, reportTitle);
    const footer = await this.generateReportFooter(workspaceId);
    const styles = await this.generateReportStyles(workspaceId);

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${reportTitle}</title>
  ${styles}
</head>
<body>
  <div class="report-container">
    ${header}
    <div class="report-content">
      ${reportContent}
    </div>
    ${footer}
  </div>
</body>
</html>
    `.trim();
  }

  /**
   * Generate CSV report with branding
   */
  async generateBrandedCsvHeader(workspaceId: string, reportTitle: string): Promise<string> {
    const branding = await this.getReportBranding(workspaceId);

    const lines = [
      `"${reportTitle}"`,
      `"${branding.companyName}"`,
      `"Generated on: ${new Date().toISOString()}"`,
      '', // Empty line separator
    ];

    return lines.join('\n');
  }

  /**
   * Apply watermark to report (for PDF generation)
   */
  async applyWatermark(workspaceId: string): Promise<string | null> {
    const branding = await this.getReportBranding(workspaceId);

    if (!branding.watermark) {
      return null;
    }

    return `
      <div style="
        position: fixed;
        bottom: 20px;
        right: 20px;
        opacity: 0.3;
        font-size: 10px;
        color: #6b7280;
        transform: rotate(-45deg);
        pointer-events: none;
      ">
        ${branding.watermark}
      </div>
    `;
  }
}
